language: php

# list any PHP version you want to test against
php:
  # using major version aliases

  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

install:
  - sh ./bin/prepare_tests.sh

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: ./bin/run_tests.sh

notifications:
  email:
    on_success: change
    on_failure: change